### ISSUE TITLE
Send Payments

### ISSUE THREAD

**Issue by obramen** [deluakin/hubtel-payment#2]
I've been testing your library and so far so good except for one thing. It would be great if you could include in the library, the ability to send payments besides receiving them. 
Do you have any plans for this?

**Comment by deluakin** [comment]
Thanks....I've thought about this, but am not sure I'll do this any time soon.

**Comment by AbdulRazak-Naeate** [comment]
I am trying your library but there is no response ,progress wheel just spined and stop nothing happens.

**Comment by deluakin** [comment]
Will have a look and get back to you

**Comment by AbdulRazak-Naeate** [comment]
I found out the problem, account was to be verified before .it's verified now and its connection .thanks for the brilliant code

**Comment by deluakin** [comment]
Ok great. Thanks for letting me know.
