### ISSUE TITLE
End of input at character 0 of 

### ISSUE THREAD

**Issue by ngoahamos** [deluakin/hubtel-payment#3]
Hello,
I have used this Library before, but of late i only see 
```Connecting to Hubtel```. 
Then after a few seconds it disappear with 
```
https://api.hubtel.com/v1/merchantaccount/onlinecheckout/invoice/create
End of input at character 0 of
```
At the logcat.

Any help will be much appreciated.

**Comment by deluakin** [comment]
Kindly update the library if you haven't

**Comment by ngoahamos** [comment]
Thanks for your response.
I updated it and still not working. Now getting 
```
  https://api.hubtel.com/v2/pos/onlinecheckout/items/initiate
  End of input at character 0 of

**Comment by deluakin** [comment]
Kindly share your code
