### ISSUE TITLE
Doesn't work well on Android 5.1 

### ISSUE THREAD

**Issue by nivla360** [deluakin/hubtel-payment#6]
Verification of code sent is always invalid and sometimes loads forever when sending the verification code

**Comment by deluakin** [comment]
If the button to send OTP is tapped multiple times it may result in invalid code simply because every time you click a new OTP is generated and sent. Also, with the load forever, this may have to do with your internet.

Kindly confirm if you are still experiencing the issue on said android version or other versions.

**Comment by neocodegh** [comment]
So meaning it will not work on android 6.0 and above. Very bad. After loading, the progress dialog dismisses. what is the problem?

**Comment by popekabu** [comment]
> So meaning it will not work on android 6.0 and above. Very bad. After loading, the progress dialog dismisses. what is the problem?

it works bro. he probably tapped it more than once

**Comment by neocodegh** [comment]
> > So meaning it will not work on android 6.0 and above. Very bad. After loading, the progress dialog dismisses. what is the problem?
> 
> it works bro. he probably tapped it more than once

After it loads the progress dialog exits and nothing shows.. What is suppose to be display after the progress dialog loads?

**Comment by popekabu** [comment]
Please write your entire problem and the step before the problem or send me a mail on popekabu@gmail.com

**Comment by popekabu** [comment]
i finally got the issue you mentioned here @ALI-SAMPSON. It wasnt a code issue but Hubtel had removed or suspended my account with them because we didnt have transactions for i think 3 months. And there was no notice given. So check if yours is the same too. 

Sharing to help someone too

**Comment by neocodegh** [comment]
Thanks bro...I will check it out

**Comment by deluakin** [comment]
This issue will be closed as no further comments regarding this was posted in over 2months. Do not hesitate to comment if you still encountering this issue

**Comment by popekabu** [comment]
Hmmm okay
